# yaml-language-server: $schema=../config.schema.yaml
git_config:
  personal_access_token: github_pat_1a2b3c4d5e6f7g8h9i0j1a2b3c4d5e6f7g8h9i0j
  repo_owner: your-github-org-or-username
llm_config:
  default_llm_provider: deepseek
  llm_providers:
    deepseek:
      api_key: "your-deepseek-api-key"
      client_model: "deepseek-chat"
    openrouter:
      api_key: "your-openrouter-api-key"
      client_model: "deepseek/deepseek-chat"
    thaura:
      api_key: "your-thaura-api-key"
      client_model: "thaura"
